// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9dnsJBx9JLiw4eSh68nnCy8nD2Mb7CF0',
    appId: '1:849662432906:web:ddec884f774c699306ff73',
    messagingSenderId: '849662432906',
    projectId: 'undigitally-d1bfc',
    authDomain: 'undigitally-d1bfc.firebaseapp.com',
    storageBucket: 'undigitally-d1bfc.appspot.com',
    measurementId: 'G-K7BNWZMW71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_m3M6WoFbToLe9-F6P5gGYaaAj0F8v4',
    appId: '1:849662432906:android:bd33577374975fb406ff73',
    messagingSenderId: '849662432906',
    projectId: 'undigitally-d1bfc',
    storageBucket: 'undigitally-d1bfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2e_W-NtvEjqT9iMDB-0G8jbZXLAMy6Ik',
    appId: '1:849662432906:ios:a1e578db6d230efe06ff73',
    messagingSenderId: '849662432906',
    projectId: 'undigitally-d1bfc',
    storageBucket: 'undigitally-d1bfc.appspot.com',
    iosClientId: '849662432906-vnk3pc2vhagndn9rk6qkpv1knccao2t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.initialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2e_W-NtvEjqT9iMDB-0G8jbZXLAMy6Ik',
    appId: '1:849662432906:ios:a1e578db6d230efe06ff73',
    messagingSenderId: '849662432906',
    projectId: 'undigitally-d1bfc',
    storageBucket: 'undigitally-d1bfc.appspot.com',
    iosClientId: '849662432906-vnk3pc2vhagndn9rk6qkpv1knccao2t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.initialApp',
  );
}
